### ISSUE TITLE
Accept a list of types

### ISSUE THREAD

**Issue by jmlord** [GEO-BON/bon-in-a-box-pipeline-engine#36]
For example, a script could accept type: [text/csv, text/tab-separated-values] instead of just one of them.

We expect something like this in the yml:

``` yml
input_id:
  type: 
    - text/csv
    - text/tab-separated-values
```

or 

``` yml
input_id:
  type: [text/csv, text/tab-separated-values]
```
