### ISSUE TITLE
Allow inputs to be conditional to an option

### ISSUE THREAD

**Issue by jmlord** [GEO-BON/bon-in-a-box-pipeline-engine#49]
Something like this:

```yml
  a_boolean:
    label: A boolean
    description: Optional with "first option". The description of this value
    type: boolean
    example: true
    depends_on:
      options_example: second option
  options_example:
    label: Fixed options
    description: The user has to select between a fixed number of text options. The script receives the selected option as text.
    type: options
    options:
      - first option
      - second option
      - third option
    example: third option
```

In the UI, the linked param would be enabled / appear only when the requirements are met.

Affects the yml file, the cerberus validation, the pipeline run UI and the pipeline editor UI.
